INSERT INTO country_list (Shortname, Fullname) VALUES ('AF', 'Afghanistan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AX', 'Åland Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DZ', 'Algeria (El Djazaïr)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AL', 'Albania');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AS', 'American Samoa');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AD', 'Andorra');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AO', 'Angola');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AI', 'Anguilla');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AQ', 'Antarctica');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AR', 'Argentina');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AM', 'Armenia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AW', 'Aruba');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AU', 'Australia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AT', 'Austria');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BS', 'Bahamas');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BH', 'Bahrain');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BD', 'Bangladesh');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BB', 'Barbados');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BY', 'Belarus');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BE', 'Belgium');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BZ', 'Belize');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BJ', 'Benin');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BM', 'Bermuda');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BT', 'Bhutan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BO', 'Bolivia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BW', 'Botswana');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BV', 'Bouvet Island');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BR', 'Brazil');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BG', 'Bulgaria');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BF', 'Burkina Faso');
INSERT INTO country_list (Shortname, Fullname) VALUES ('BI', 'Burundi');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KH', 'Cambodia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CM', 'Cameroon');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CA', 'Canada');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CV', 'Cape Verde');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KY', 'Cayman Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CF', 'Central African Republic');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TD', 'Chad (T''Chad)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CL', 'Chile');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CN', 'China');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CX', 'Christmas Island');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CO', 'Colombia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KM', 'Comoros');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CG', 'Congo, Republic Of');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CD', 'Congo, The Democratic Republic of the (formerly Zaire)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CK', 'Cook Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CR', 'Costa Rica');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CI', 'CÔte D''Ivoire (Ivory Coast)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HR', 'Croatia (hrvatska)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CU', 'Cuba');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CY', 'Cyprus');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CZ', 'Czech Republic');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DK', 'Denmark');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DJ', 'Djibouti');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DM', 'Dominica');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DO', 'Dominican Republic');
INSERT INTO country_list (Shortname, Fullname) VALUES ('EC', 'Ecuador');
INSERT INTO country_list (Shortname, Fullname) VALUES ('EG', 'Egypt');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SV', 'El Salvador');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ER', 'Eritrea');
INSERT INTO country_list (Shortname, Fullname) VALUES ('EE', 'Estonia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ET', 'Ethiopia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FO', 'Faeroe Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FJ', 'Fiji');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FI', 'Finland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FR', 'France');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GF', 'French Guiana');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PF', 'French Polynesia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TF', 'French Southern Territories');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GA', 'Gabon');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GM', 'Gambia, The');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GE', 'Georgia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('DE', 'Germany (Deutschland)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GH', 'Ghana');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GI', 'Gibraltar');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GR', 'Greece');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GL', 'Greenland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GD', 'Grenada');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GP', 'Guadeloupe');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GU', 'Guam');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GT', 'Guatemala');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GN', 'Guinea');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GW', 'Guinea-bissau');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GY', 'Guyana');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HT', 'Haiti');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HM', 'Heard Island and Mcdonald Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HN', 'Honduras');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HK', 'Hong Kong (Special Administrative Region of China)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('HU', 'Hungary');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IS', 'Iceland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IN', 'India');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ID', 'Indonesia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IR', 'Iran (Islamic Republic of Iran)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IQ', 'Iraq');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IE', 'Ireland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IL', 'Israel');
INSERT INTO country_list (Shortname, Fullname) VALUES ('IT', 'Italy');
INSERT INTO country_list (Shortname, Fullname) VALUES ('JM', 'Jamaica');
INSERT INTO country_list (Shortname, Fullname) VALUES ('JP', 'Japan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('JO', 'Jordan (Hashemite Kingdom of Jordan)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KE', 'Kenya');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KI', 'Kiribati');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KP', 'Korea (Democratic Peoples Republic pf [North] Korea)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KR', 'Korea (Republic of [South] Korea)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KW', 'Kuwait');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LV', 'Latvia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LB', 'Lebanon');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LS', 'Lesotho');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LR', 'Liberia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LY', 'Libya (Libyan Arab Jamahirya)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LI', 'Liechtenstein (Fürstentum Liechtenstein)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LT', 'Lithuania');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LU', 'Luxembourg');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MO', 'Macao (Special Administrative Region of China)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MK', 'Macedonia (Former Yugoslav Republic of Macedonia)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MG', 'Madagascar');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MW', 'Malawi');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MY', 'Malaysia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MV', 'Maldives');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ML', 'Mali');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MT', 'Malta');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MH', 'Marshall Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MQ', 'Martinique');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MR', 'Mauritania');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MU', 'Mauritius');
INSERT INTO country_list (Shortname, Fullname) VALUES ('YT', 'Mayotte');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MX', 'Mexico');
INSERT INTO country_list (Shortname, Fullname) VALUES ('FM', 'Micronesia (Federated States of Micronesia)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MD', 'Moldova');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MC', 'Monaco');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MN', 'Mongolia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MS', 'Montserrat');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MA', 'Morocco');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MZ', 'Mozambique (Moçambique)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MM', 'Myanmar (formerly Burma)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NA', 'Namibia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NR', 'Nauru');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NP', 'Nepal');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NL', 'Netherlands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NC', 'New Caledonia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NZ', 'New Zealand');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NI', 'Nicaragua');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NE', 'Niger');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NG', 'Nigeria');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NU', 'Niue');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NF', 'Norfolk Island');
INSERT INTO country_list (Shortname, Fullname) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('NO', 'Norway');
INSERT INTO country_list (Shortname, Fullname) VALUES ('OM', 'Oman');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PK', 'Pakistan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PW', 'Palau');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PS', 'Palestinian Territories');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PA', 'Panama');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PG', 'Papua New Guinea');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PY', 'Paraguay');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PE', 'Peru');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PH', 'Philippines');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PN', 'Pitcairn');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PL', 'Poland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PT', 'Portugal');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PR', 'Puerto Rico');
INSERT INTO country_list (Shortname, Fullname) VALUES ('QA', 'Qatar');
INSERT INTO country_list (Shortname, Fullname) VALUES ('RE', 'RÉunion');
INSERT INTO country_list (Shortname, Fullname) VALUES ('RO', 'Romania');
INSERT INTO country_list (Shortname, Fullname) VALUES ('RU', 'Russian Federation');
INSERT INTO country_list (Shortname, Fullname) VALUES ('RW', 'Rwanda');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SH', 'Saint Helena');
INSERT INTO country_list (Shortname, Fullname) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LC', 'Saint Lucia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO country_list (Shortname, Fullname) VALUES ('WS', 'Samoa (formerly Western Samoa)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SM', 'San Marino (Republic of)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SA', 'Saudi Arabia (Kingdom of Saudi Arabia)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SN', 'Senegal');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CS', 'Serbia and Montenegro (formerly Yugoslavia)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SC', 'Seychelles');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SL', 'Sierra Leone');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SG', 'Singapore');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SK', 'Slovakia (Slovak Republic)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SI', 'Slovenia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SB', 'Solomon Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SO', 'Somalia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ZA', 'South Africa (zuid Afrika)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ES', 'Spain (españa)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('LK', 'Sri Lanka');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SD', 'Sudan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SR', 'Suriname');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SZ', 'Swaziland');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SE', 'Sweden');
INSERT INTO country_list (Shortname, Fullname) VALUES ('CH', 'Switzerland (Confederation of Helvetia)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TW', 'Taiwan ("Chinese Taipei" for IOC)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TJ', 'Tajikistan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TZ', 'Tanzania');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TH', 'Thailand');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TL', 'Timor-Leste (formerly East Timor)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TG', 'Togo');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TK', 'Tokelau');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TO', 'Tonga');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TN', 'Tunisia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TR', 'Turkey');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TM', 'Turkmenistan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('TV', 'Tuvalu');
INSERT INTO country_list (Shortname, Fullname) VALUES ('UG', 'Uganda');
INSERT INTO country_list (Shortname, Fullname) VALUES ('UA', 'Ukraine');
INSERT INTO country_list (Shortname, Fullname) VALUES ('AE', 'United Arab Emirates');
INSERT INTO country_list (Shortname, Fullname) VALUES ('GB', 'United Kingdom (Great Britain)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('US', 'United States');
INSERT INTO country_list (Shortname, Fullname) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO country_list (Shortname, Fullname) VALUES ('UY', 'Uruguay');
INSERT INTO country_list (Shortname, Fullname) VALUES ('UZ', 'Uzbekistan');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VU', 'Vanuatu');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VA', 'Vatican City (Holy See)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VE', 'Venezuela');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VN', 'Viet Nam');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VG', 'Virgin Islands, British');
INSERT INTO country_list (Shortname, Fullname) VALUES ('VI', 'Virgin Islands, U.S.');
INSERT INTO country_list (Shortname, Fullname) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO country_list (Shortname, Fullname) VALUES ('EH', 'Western Sahara (formerly Spanish Sahara)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('YE', 'Yemen (Arab Republic)');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ZM', 'Zambia');
INSERT INTO country_list (Shortname, Fullname) VALUES ('ZW', 'Zimbabwe');
